site:
  title: Epic Remastered
  # Antora generates the 404 page and sitemap files only when the `url` property is set.
  url: 
  start_page: core::index.adoc
output:
  clean: true
content:
  sources:
  - url: ../er-contributors-guide
    branches: HEAD
    # Set `edit_url` to `false` to disable the 'Edit this Page' link for any page [all pages?] that originates from this repository.
    # You can achieve the same thing if you add empty credentials (simply `@`) in front of the domain in the URL.
    edit_url: false
  - url: ../er-core
    branches: HEAD
    start_path:
  - url: ../er-battles
    branches: HEAD
    start_path:
  - url: ../er-armies
    branches: HEAD
    start_path: 
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  output_dir: assets
  # The default '_' directory for assets is problematic when building the Android app.
  supplemental_files: ./supplemental-ui
runtime:
  cache_dir: ./.cache/antora
asciidoc: 
  attributes:
    project-name: <i>Epic Remastered</i>
    uri-project: https://epicremastered.com
    uri-project-team: https://github.com/orgs/GameBrains/teams/er-project-team
    uri-builder: https://builder.epicremastered.com
    page-pagination: true
    icons: font

    # Orders and conditions with graphics, for inline usage
    assault-orders: image:core:main-rules:Orders_Assault.png[width=16,height=16] Assault orders
    march-orders: image:core:main-rules:Orders_March.png[width=16,height=16] March orders
    overwatch-orders: image:core:main-rules:Orders_Overwatch.png[width=16,height=16] Overwatch orders
    special-orders: image:core:main-rules:Orders_Special.png[width=16,height=16] Special orders   
    broken-condition: image:core:main-rules:Conditions_Broken.png[width=16,height=16] Broken condition
    immobilised-condition: image:core:main-rules:Conditions_Immobilised.png[width=16,height=16] Immobilised condition

    # Ability/vehicle variant keywords
    a-dying-race: <i>A Dying Race</i>
    anti-personnel: <i>Anti-personnel</i>
    armour-1: <i>Armour +1</i>
    artillery: <i>Artillery</i>
    assault: <i>Assault</i>
    assault-1: <i>Assault +1</i>
    bridge: <i>Bridge</i>
    brood-telepathy: <i>Brood Telepathy</i>
    cavalry: <i>Cavalry</i>
    close-support: <i>Close Support</i>
    dauntless: <i>Dauntless</i>
    deathwing: <i>Deathwing</i>
    dodge: <i>Dodge</i>
    engineers: <i>Engineers</i>
    fast: <i>Fast</i>
    flak: <i>Flak</i>
    flak-battery: <i>Flak Battery</i>
    firepower-1: <i>Firepower +1</i>
    heavy-weapons: <i>Heavy Weapons</i>
    hero: <i>Hero</i>
    hit-and-run: <i>Hit and Run</i>
    hitch-1: <i>Hitch (1)</i>
    hitch-2: <i>Hitch (2)</i>
    hitch-3: <i>Hitch (3)</i>
    hitch-4: <i>Hitch (4)</i>
    hitch-x: <i>Hitch (X)</i>
    holo-fields: <i>Holo-fields</i>
    ignore-terrain: <i>Ignore Terrain</i>
    infiltrators: <i>Infiltrators</i>
    jump-packs: <i>Jump Packs</i>
    jungle-fighters: <i>Jungle Fighters</i>
    kroot: <i>Kroot</i>
    long-range: <i>Long Range</i>
    macro-weapon: <i>Macro-weapon</i>
    medic: <i>Medic</i>
    no-retreat: <i>No Retreat</i>
    open-top: <i>Open Top</i>
    ordo-malleus: <i>Ordo Malleus</i>
    ork-initiative: <i>Ork Initiative</i>
    psychic-beacon: <i>Psychic Beacon</i>
    psyker: <i>Psyker</i>
    rampage: <i>Rampage</i>
    rapid-fire: <i>Rapid Fire</i>
    ravenwing: <i>Ravenwing</i>
    recovery: <i>Recovery</i>
    regroup: <i>Regroup</i>
    robust: <i>Robust</i>
    save: <i>Save</i>
    self-propelled-artillery: <Self-propelled Artillery</i>
    shootier: <i>Shootier</i>
    skimmer: <i>Skimmer</i>
    space-wolves: <i>Space Wolves</i>
    stubborn: <i>Stubborn</i>
    summon: <i>Summon</i>
    supreme-commander: <i>Supreme Commander</i>
    synapse: <i>Synapse</i>
    synapse-creature: <i>Synapse Creature</i>
    transport: <i>Transport</i>
    transport-1: <i>Transport (1)</i>
    transport-2: <i>Transport (2)</i>
    transport-x: <i>Transport (X)</i>
    tunneller: <i>Tunneller</i>
    unbreakable: <i>Unbreakable</i>
    walker: <i>Walker</i>

    # 'Has {super-heavy weapon}' ability keywords
    has-super-heavy-weapon: <i>Has {super-heavy weapon}</i>
    has-barrage: <i>Has Barrage</i>
    has-death-ray: <i>Has Death Ray</i>
    has-disrupt: <i>Has Disrupt</i>
    has-macro-weapon: <i>Has Macro-weapon</i>
    has-super-lifta-droppa: <i>Has Super Lifta-droppa</i>
    
    # Super-heavy weapon keywords
    anti-tank: <i>Anti-tank</i>
    barrage: <i>Barrage</i>
    close-combat-weapons: <i>Close Combat Weapons</i>
    death-ray: <i>Death Ray</i>
    deathstrike-missile: <i>Deathstrike Missile</i>
    disrupt: <i>Disrupt</i>
    distortion-cannon: <i>Distortion Cannon</i>
    heavy-barrage: <i>Heavy Barrage</i>
    mega-cannon: <i>Mega-cannon</i>
    pulsar: <i>Pulsar</i>
    ripper-tentacles: <i>Ripper Tentacles</i>
    siege: <i>Siege</i>
    super-lifta-droppa: <i>Super Lifta-droppa</i>
    tank-destroyer: <i>Tank Destroyer</i>
    vortex-missile: <i>Vortex Missile</i>